### ISSUE TITLE
Feature request: Support Graalvm

### ISSUE THREAD

**Issue by oo00spy00oo** [micronaut-projects/micronaut-cassandra#82] opened 2020-10-01 17:26 UTC
### Expected Behaviour

`micronaut-cassandra` support GraalVM build!

### Actual Behaviour
```
INFO[0095] Running: [/bin/sh -c native-image -cp build/libs/transaction-history-service-*-all.jar] 
[transaction-history-service:91]    classlist:  20,353.05 ms,  1.18 GB
[transaction-history-service:91]        setup:     793.01 ms,  1.18 GB
Error: could not find target method: protected io.netty.buffer.ByteBuf com.datastax.oss.driver.internal.core.protocol.Lz4Substitution.compressHeap(io.netty.buffer.ByteBuf)
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 1
```

**Comment by ilopmar** [comment] 2020-10-01 17:43
Duplicate of #41

**Closed by ilopmar** 2020-10-01 17:43 UTC
Labels: closed: duplicate
